const UPDATE_STAGE = 'app/editor/UPDATE_STAGE'
const UPDATE_CURRENT_EDITOR_ACTION = 'app/editor/UPDATE_CURRENT_EDITOR_ACTION'
const UPDATE_CURSOR_POSITION = 'app/editor/UPDATE_CURSOR_POSITION'

export { UPDATE_CURRENT_EDITOR_ACTION, UPDATE_CURSOR_POSITION, UPDATE_STAGE }
