const SET_PROJECT_LIST = 'app/projects/SET_PROJECT_LIST'
const SELECT_PROJECT_BY_ID = 'app/projects/SELECT_PROJECT_BY_ID'
const REQUEST_PROJECT_LIST = 'app/projects/REQUEST_PROJECT_LIST'
const UPDATE_PROJECT_BY_ID = 'app/projects/UPDATE_PROJECT_BY_ID'
const DELETE_PROJECT_BY_ID = 'app/projects/DELETE_PROJECT_BY_ID'
const GET_PROJECT_BY_ID = 'app/projects/SELECT_PROJECT_BY_ID'
const CREATE_PROJECT = 'app/projects/CREATE_PROJECT'

export {
  CREATE_PROJECT,
  DELETE_PROJECT_BY_ID,
  GET_PROJECT_BY_ID,
  REQUEST_PROJECT_LIST,
  SELECT_PROJECT_BY_ID,
  SET_PROJECT_LIST,
  UPDATE_PROJECT_BY_ID,
}
