const CREATE_NODE = 'app/editor/CREATE_NODE'
const SELECT_NODE = 'app/editor/SELECT_NODE'
const UNSELECT_NODE = 'app/editor/UNSELECT_NODE'
const DELETE_NODE = 'app/editor/DELETE_NODE'
const UPDATE_CURSOR_POSITION = 'app/editor/UPDATE_CURSOR_POSITION'
const UPDATE_NODE_POSITION_START = 'app/editor/UPDATE_NODE_POSITION_START'
const UPDATE_NODE_POSITION_END = 'app/editor/UPDATE_NODE_POSITION_END'
const DRAW_TEMP_ARROW = 'app/editor/DRAW_TEMP_ARROW'
const UPDATE_STAGE_POSITION = 'app/editor/UPDATE_STAGE_POSITION'
const CREATE_ARROW = 'app/editor/CREATE_ARROW'
const UPDATE_ARROW_POSITION = 'app/editor/UPDATE_ARROW_POSITION'
const SELECT_ARROW = 'app/editor/SELECT_ARROW'
const UNSELECT_ARROW = 'app/editor/UNSELECT_ARROW'
const DELETE_ARROW = 'app/editor/DELETE_ARROW'
const MULTI_SELECT = 'app/editor/MULTI_SELECT'

const DELETE_SHAPE = 'app/editor/DELETE_SHAPE'
const CREATE_SHAPE = 'app/editor/CREATE_SHAPE'

const SCALE_STAGE = 'app/editor/SCALE_STAGE'

const CHANGE_EDITOR_ACTION_TYPE = 'app/editor/CHANGE_EDITOR_ACTION_TYPE'

const INIT_HISTORY = '@@redux-undo/INIT'
const LOAD_STATE = 'app/editor/LOAD_STATE'

const UPDATE_NODE_NAME = 'app/editor/UPDATE_NODE_NAME'
const UPDATE_ARROW_WEIGHT = 'app/editor/UPDATE_ARROW_WEIGHT'

const UNDO_EDITOR_HISTORY = 'app/editor/UNDO_EDITOR_HISTORY'
const REDO_EDITOR_HISTORY = 'app/editor/REDO_EDITOR_HISTORY'
const INIT_EDITOR_HISTORY = 'app/editor/INIT_EDITOR_HISTORY'
const SET_INITIAL_NODE = 'app/editor/SET_INITIAL_NODE'

export {
  CHANGE_EDITOR_ACTION_TYPE,
  CREATE_ARROW,
  CREATE_NODE,
  CREATE_SHAPE,
  DELETE_ARROW,
  DELETE_NODE,
  DELETE_SHAPE,
  DRAW_TEMP_ARROW,
  INIT_EDITOR_HISTORY,
  INIT_HISTORY,
  LOAD_STATE,
  MULTI_SELECT,
  REDO_EDITOR_HISTORY,
  SELECT_ARROW,
  SCALE_STAGE,
  SET_INITIAL_NODE,
  SELECT_NODE,
  UNDO_EDITOR_HISTORY,
  UNSELECT_ARROW,
  UNSELECT_NODE,
  UPDATE_ARROW_POSITION,
  UPDATE_ARROW_WEIGHT,
  UPDATE_CURSOR_POSITION,
  UPDATE_NODE_NAME,
  UPDATE_NODE_POSITION_END,
  UPDATE_NODE_POSITION_START,
  UPDATE_STAGE_POSITION,
}
