const START_PLAYING = 'app/algorithm/START_PLAYING'
const STOP_PLAYING = 'app/algorithm/STOP_PLAYING'
const NEXT_ITERATION = 'app/algorithm/NEXT_ITERATION'
const PREVIOUS_ITERATION = 'app/algorithm/PREVIOUS_ITERATION'
const FIRST_ITERATION = 'app/algorithm/FIRST_ITERATION'
const LAST_ITERATION = 'app/algorithm/LAST_ITERATION'

export {
  FIRST_ITERATION,
  LAST_ITERATION,
  NEXT_ITERATION,
  PREVIOUS_ITERATION,
  START_PLAYING,
  STOP_PLAYING,
}
