const CREATE_NODE = 'app/graph/CREATE_NODE'
const DELETE_NODE = 'app/graph/DELETE_NODE'
const SELECT_NODE = 'app/graph/SELECT_NODE'
const UNSELECT_NODE = 'app/graph/UNSELECT_NODE'
const UPDATE_NODE_POSITION_START = 'app/graph/UPDATE_NODE_POSITION_START'
const UPDATE_NODE_POSITION_END = 'app/graph/UPDATE_NODE_POSITION_END'
const UPDATE_NODE_PROPERTIES = 'app/graph/UPDATE_NODE_PROPERTIES'

const CREATE_EDGE = 'app/graph/CREATE_EDGE'
const DELETE_EDGE = 'app/graph/DELETE_EDGE'
const SELECT_EDGE = 'app/graph/SELECT_EDGE'
const UNSELECT_EDGE = 'app/graph/UNSELECT_EDGE'
const UPDATE_EDGE_PROPERTIES = 'app/graph/UPDATE_EDGE_PROPERTIES'

const UPDATE_METADATA = 'app/graph/UPDATE_METADATA'

const LOAD_GRAPH = 'app/graph/LOAD_GRAPH'
const UNDO_GRAPH_HISTORY = 'app/graph/UNDO_GRAPH_HISTORY'
const REDO_GRAPH_HISTORY = 'app/graph/REDO_GRAPH_HISTORY'
const INIT_GRAPH_HISTORY = 'app/graph/INIT_GRAPH_HISTORY'

export {
  CREATE_EDGE,
  CREATE_NODE,
  DELETE_EDGE,
  DELETE_NODE,
  INIT_GRAPH_HISTORY,
  LOAD_GRAPH,
  REDO_GRAPH_HISTORY,
  SELECT_EDGE,
  SELECT_NODE,
  UNDO_GRAPH_HISTORY,
  UNSELECT_EDGE,
  UNSELECT_NODE,
  UPDATE_EDGE_PROPERTIES,
  UPDATE_METADATA,
  UPDATE_NODE_POSITION_END,
  UPDATE_NODE_POSITION_START,
  UPDATE_NODE_PROPERTIES,
}
